package vvgtest.ja;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Analiza implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("AnalizaID")
   private java.lang.Long id_analize;
   @org.kie.api.definition.type.Label("OznakaUC")
   private java.lang.String oznaka_UC;

   @org.kie.api.definition.type.Label("naziv UC")
   private java.lang.String naziv_UC;

   @org.kie.api.definition.type.Label("opisivanje poslovnih pravila")
   private java.lang.String opis_uc;

   @org.kie.api.definition.type.Label("ZahtjevID")
   private java.lang.Long id_zahtjeva;

   @org.kie.api.definition.type.Label(value = "Narucitelj")
   private java.lang.String narucitelj;

   @org.kie.api.definition.type.Label(value = "Korisnik koji unosi podatke")
   private java.lang.Long id_korisnika;

   public Analiza()
   {
   }

   public java.lang.Long getId_analize()
   {
      return this.id_analize;
   }

   public void setId_analize(java.lang.Long id_analize)
   {
      this.id_analize = id_analize;
   }

   public java.lang.String getOznaka_UC()
   {
      return this.oznaka_UC;
   }

   public void setOznaka_UC(java.lang.String oznaka_UC)
   {
      this.oznaka_UC = oznaka_UC;
   }

   public java.lang.String getNaziv_UC()
   {
      return this.naziv_UC;
   }

   public void setNaziv_UC(java.lang.String naziv_UC)
   {
      this.naziv_UC = naziv_UC;
   }

   public java.lang.String getOpis_uc()
   {
      return this.opis_uc;
   }

   public void setOpis_uc(java.lang.String opis_uc)
   {
      this.opis_uc = opis_uc;
   }

   public java.lang.Long getId_zahtjeva()
   {
      return this.id_zahtjeva;
   }

   public void setId_zahtjeva(java.lang.Long id_zahtjeva)
   {
      this.id_zahtjeva = id_zahtjeva;
   }

   public java.lang.String getNarucitelj()
   {
      return this.narucitelj;
   }

   public void setNarucitelj(java.lang.String narucitelj)
   {
      this.narucitelj = narucitelj;
   }

   public java.lang.Long getId_korisnika()
   {
      return this.id_korisnika;
   }

   public void setId_korisnika(java.lang.Long id_korisnika)
   {
      this.id_korisnika = id_korisnika;
   }

   public Analiza(java.lang.Long id_analize, java.lang.String oznaka_UC,
         java.lang.String naziv_UC, java.lang.String opis_uc,
         java.lang.Long id_zahtjeva, java.lang.String narucitelj,
         java.lang.Long id_korisnika)
   {
      this.id_analize = id_analize;
      this.oznaka_UC = oznaka_UC;
      this.naziv_UC = naziv_UC;
      this.opis_uc = opis_uc;
      this.id_zahtjeva = id_zahtjeva;
      this.narucitelj = narucitelj;
      this.id_korisnika = id_korisnika;
   }

}