package vvgtest.ja;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Isporuka_u_test implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   public Isporuka_u_test()
   {
   }

}