package vvgtest.ja;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Izvjestaji implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("IzjestajID")
   private java.lang.Long id_izvjestaja;
   @org.kie.api.definition.type.Label("ZahtjevID")
   private Zahtjevi id_zahtjeva;
   @org.kie.api.definition.type.Label("TestnaSkriptaID")
   private Testne_sripte id_testne_skripte;
   @org.kie.api.definition.type.Label("naziv")
   private java.lang.String naziv;
   @org.kie.api.definition.type.Label("opis")
   private java.lang.String opis;
   @org.kie.api.definition.type.Label("korisnika")
   private Korisnici id_korisnika;

   public Izvjestaji()
   {
   }

   public java.lang.Long getId_izvjestaja()
   {
      return this.id_izvjestaja;
   }

   public void setId_izvjestaja(java.lang.Long id_izvjestaja)
   {
      this.id_izvjestaja = id_izvjestaja;
   }

   public java.lang.String getNaziv()
   {
      return this.naziv;
   }

   public void setNaziv(java.lang.String naziv)
   {
      this.naziv = naziv;
   }

   public java.lang.String getOpis()
   {
      return this.opis;
   }

   public void setOpis(java.lang.String opis)
   {
      this.opis = opis;
   }

   public vvgtest.ja.Korisnici getId_korisnika()
   {
      return this.id_korisnika;
   }

   public void setId_korisnika(vvgtest.ja.Korisnici id_korisnika)
   {
      this.id_korisnika = id_korisnika;
   }

   public vvgtest.ja.Testne_sripte getId_testne_skripte()
   {
      return this.id_testne_skripte;
   }

   public void setId_testne_skripte(vvgtest.ja.Testne_sripte id_testne_skripte)
   {
      this.id_testne_skripte = id_testne_skripte;
   }

   public vvgtest.ja.Zahtjevi getId_zahtjeva()
   {
      return this.id_zahtjeva;
   }

   public void setId_zahtjeva(vvgtest.ja.Zahtjevi id_zahtjeva)
   {
      this.id_zahtjeva = id_zahtjeva;
   }

   public Izvjestaji(java.lang.Long id_izvjestaja,
         vvgtest.ja.Zahtjevi id_zahtjeva,
         vvgtest.ja.Testne_sripte id_testne_skripte, java.lang.String naziv,
         java.lang.String opis, vvgtest.ja.Korisnici id_korisnika)
   {
      this.id_izvjestaja = id_izvjestaja;
      this.id_zahtjeva = id_zahtjeva;
      this.id_testne_skripte = id_testne_skripte;
      this.naziv = naziv;
      this.opis = opis;
      this.id_korisnika = id_korisnika;
   }

}