package vvgtest.ja;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Korisnici implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("KorisnikID")
   private java.lang.Long id_korisnika;
   @org.kie.api.definition.type.Label("Ime")
   private java.lang.String ime_korisnik;
   @org.kie.api.definition.type.Label("Prezime")
   private java.lang.String prezime_korisnika;
   @org.kie.api.definition.type.Label("Korisnicko ime")
   private java.lang.String korisnicko_ime;
   @org.kie.api.definition.type.Label("Lozinka")
   private java.lang.String lozinka;

   public Korisnici()
   {
   }

   public java.lang.Long getId_korisnika()
   {
      return this.id_korisnika;
   }

   public void setId_korisnika(java.lang.Long id_korisnika)
   {
      this.id_korisnika = id_korisnika;
   }

   public java.lang.String getIme_korisnik()
   {
      return this.ime_korisnik;
   }

   public void setIme_korisnik(java.lang.String ime_korisnik)
   {
      this.ime_korisnik = ime_korisnik;
   }

   public java.lang.String getPrezime_korisnika()
   {
      return this.prezime_korisnika;
   }

   public void setPrezime_korisnika(java.lang.String prezime_korisnika)
   {
      this.prezime_korisnika = prezime_korisnika;
   }

   public java.lang.String getKorisnicko_ime()
   {
      return this.korisnicko_ime;
   }

   public void setKorisnicko_ime(java.lang.String korisnicko_ime)
   {
      this.korisnicko_ime = korisnicko_ime;
   }

   public java.lang.String getLozinka()
   {
      return this.lozinka;
   }

   public void setLozinka(java.lang.String lozinka)
   {
      this.lozinka = lozinka;
   }

   public Korisnici(java.lang.Long id_korisnika, java.lang.String ime_korisnik,
         java.lang.String prezime_korisnika, java.lang.String korisnicko_ime,
         java.lang.String lozinka)
   {
      this.id_korisnika = id_korisnika;
      this.ime_korisnik = ime_korisnik;
      this.prezime_korisnika = prezime_korisnika;
      this.korisnicko_ime = korisnicko_ime;
      this.lozinka = lozinka;
   }

}