package vvgtest.ja;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Korisnici implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("KorisnikID")
   private java.lang.Long id_korisnika;
   @org.kie.api.definition.type.Label("Ime")
   private java.lang.String ime_korisnik;
   @org.kie.api.definition.type.Label("Prezime")
   private java.lang.String prezime_korisnika;
   @org.kie.api.definition.type.Label("Korisnicko ime")
   private java.lang.String korisnicko_ime;
   @org.kie.api.definition.type.Label("Lozinka")
   private java.lang.String lozinka;

   @org.kie.api.definition.type.Label("mail adresa korisnika")
   private java.lang.Long mail_adresa;

   @org.kie.api.definition.type.Label("ovlast_korisnika")
   private ovlasti id_ovlasti;

   @org.kie.api.definition.type.Label(value = "aktivnost")
   private java.lang.Boolean aktivnost;

   public Korisnici()
   {
   }

   public java.lang.Long getId_korisnika()
   {
      return this.id_korisnika;
   }

   public void setId_korisnika(java.lang.Long id_korisnika)
   {
      this.id_korisnika = id_korisnika;
   }

   public java.lang.String getIme_korisnik()
   {
      return this.ime_korisnik;
   }

   public void setIme_korisnik(java.lang.String ime_korisnik)
   {
      this.ime_korisnik = ime_korisnik;
   }

   public java.lang.String getPrezime_korisnika()
   {
      return this.prezime_korisnika;
   }

   public void setPrezime_korisnika(java.lang.String prezime_korisnika)
   {
      this.prezime_korisnika = prezime_korisnika;
   }

   public java.lang.String getKorisnicko_ime()
   {
      return this.korisnicko_ime;
   }

   public void setKorisnicko_ime(java.lang.String korisnicko_ime)
   {
      this.korisnicko_ime = korisnicko_ime;
   }

   public java.lang.String getLozinka()
   {
      return this.lozinka;
   }

   public void setLozinka(java.lang.String lozinka)
   {
      this.lozinka = lozinka;
   }

   public java.lang.Long getMail_adresa()
   {
      return this.mail_adresa;
   }

   public void setMail_adresa(java.lang.Long mail_adresa)
   {
      this.mail_adresa = mail_adresa;
   }

   public vvgtest.ja.ovlasti getId_ovlasti()
   {
      return this.id_ovlasti;
   }

   public void setId_ovlasti(vvgtest.ja.ovlasti id_ovlasti)
   {
      this.id_ovlasti = id_ovlasti;
   }

   public java.lang.Boolean getAktivnost()
   {
      return this.aktivnost;
   }

   public void setAktivnost(java.lang.Boolean aktivnost)
   {
      this.aktivnost = aktivnost;
   }

   public Korisnici(java.lang.Long id_korisnika, java.lang.String ime_korisnik,
         java.lang.String prezime_korisnika, java.lang.String korisnicko_ime,
         java.lang.String lozinka, java.lang.Long mail_adresa,
         vvgtest.ja.ovlasti id_ovlasti, java.lang.Boolean aktivnost)
   {
      this.id_korisnika = id_korisnika;
      this.ime_korisnik = ime_korisnik;
      this.prezime_korisnika = prezime_korisnika;
      this.korisnicko_ime = korisnicko_ime;
      this.lozinka = lozinka;
      this.mail_adresa = mail_adresa;
      this.id_ovlasti = id_ovlasti;
      this.aktivnost = aktivnost;
   }

}