package vvgtest.ja;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ovlasti implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "ovlastID")
   private java.lang.Integer id_ovlast;
   @org.kie.api.definition.type.Label(value = "administrator")
   private java.lang.String admin;

   public ovlasti()
   {
   }

   public java.lang.Integer getId_ovlast()
   {
      return this.id_ovlast;
   }

   public void setId_ovlast(java.lang.Integer id_ovlast)
   {
      this.id_ovlast = id_ovlast;
   }

   public java.lang.String getAdmin()
   {
      return this.admin;
   }

   public void setAdmin(java.lang.String admin)
   {
      this.admin = admin;
   }

   public ovlasti(java.lang.Integer id_ovlast, java.lang.String admin)
   {
      this.id_ovlast = id_ovlast;
      this.admin = admin;
   }

}