package vvgtest.ja;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Pogreske implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Pogreske() {
    }

}