package vvgtest.ja;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Prijava_korisnika implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Prijava_korisnika() {
    }

}