package vvgtest.ja;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Prijava_korisnika implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "PrijavaID")
   private java.lang.Integer id_prijave;
   @org.kie.api.definition.type.Label(value = "Korisnicko ime")
   private java.lang.String username;
   @org.kie.api.definition.type.Label(value = "Lozinka")
   private java.lang.String lozinka;

   public Prijava_korisnika()
   {
   }

   public java.lang.Integer getId_prijave()
   {
      return this.id_prijave;
   }

   public void setId_prijave(java.lang.Integer id_prijave)
   {
      this.id_prijave = id_prijave;
   }

   public java.lang.String getUsername()
   {
      return this.username;
   }

   public void setUsername(java.lang.String username)
   {
      this.username = username;
   }

   public java.lang.String getLozinka()
   {
      return this.lozinka;
   }

   public void setLozinka(java.lang.String lozinka)
   {
      this.lozinka = lozinka;
   }

   public Prijava_korisnika(java.lang.Integer id_prijave,
         java.lang.String username, java.lang.String lozinka)
   {
      this.id_prijave = id_prijave;
      this.username = username;
      this.lozinka = lozinka;
   }

}