package vvgtest.ja;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Programiranje implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long id_programiranje;
   private vvgtest.ja.Analiza id_analize;
   private java.lang.String preuzeta_dokuemtacija;

   public Programiranje()
   {
   }

   public java.lang.Long getId_programiranje()
   {
      return this.id_programiranje;
   }

   public void setId_programiranje(java.lang.Long id_programiranje)
   {
      this.id_programiranje = id_programiranje;
   }

   public vvgtest.ja.Analiza getId_analize()
   {
      return this.id_analize;
   }

   public void setId_analize(vvgtest.ja.Analiza id_analize)
   {
      this.id_analize = id_analize;
   }

   public java.lang.String getPreuzeta_dokuemtacija()
   {
      return this.preuzeta_dokuemtacija;
   }

   public void setPreuzeta_dokuemtacija(java.lang.String preuzeta_dokuemtacija)
   {
      this.preuzeta_dokuemtacija = preuzeta_dokuemtacija;
   }

   public Programiranje(java.lang.Long id_programiranje,
         vvgtest.ja.Analiza id_analize,
         java.lang.String preuzeta_dokuemtacija)
   {
      this.id_programiranje = id_programiranje;
      this.id_analize = id_analize;
      this.preuzeta_dokuemtacija = preuzeta_dokuemtacija;
   }

}