package vvgtest.ja;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Programiranje implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Programiranje() {
    }

}