package vvgtest.ja;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Statusi_pogresaka implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "statusPogresakaID")
   private java.lang.Long id_sts_pogr;
   @org.kie.api.definition.type.Label(value = "Prijavljena")
   private java.lang.String prijavljena;
   @org.kie.api.definition.type.Label(value = "U obradi")
   private java.lang.String u_obradi;
   @org.kie.api.definition.type.Label(value = "Ispravio programer")
   private java.lang.String ispravljena_programer;
   @org.kie.api.definition.type.Label(value = "Provjerena/ispravljena")
   private java.lang.String provjerena;
   @org.kie.api.definition.type.Label(value = "Zatvorena")
   private java.lang.String zatvorena;
   @org.kie.api.definition.type.Label(value = "Ponovno otvorena")
   private java.lang.String ponovno_otvorena;
   @org.kie.api.definition.type.Label(value = "Vracena u obradu")
   private java.lang.String vracena_u_obradu;

   public Statusi_pogresaka()
   {
   }

   public java.lang.Long getId_sts_pogr()
   {
      return this.id_sts_pogr;
   }

   public void setId_sts_pogr(java.lang.Long id_sts_pogr)
   {
      this.id_sts_pogr = id_sts_pogr;
   }

   public java.lang.String getPrijavljena()
   {
      return this.prijavljena;
   }

   public void setPrijavljena(java.lang.String prijavljena)
   {
      this.prijavljena = prijavljena;
   }

   public java.lang.String getU_obradi()
   {
      return this.u_obradi;
   }

   public void setU_obradi(java.lang.String u_obradi)
   {
      this.u_obradi = u_obradi;
   }

   public java.lang.String getIspravljena_programer()
   {
      return this.ispravljena_programer;
   }

   public void setIspravljena_programer(java.lang.String ispravljena_programer)
   {
      this.ispravljena_programer = ispravljena_programer;
   }

   public java.lang.String getProvjerena()
   {
      return this.provjerena;
   }

   public void setProvjerena(java.lang.String provjerena)
   {
      this.provjerena = provjerena;
   }

   public java.lang.String getZatvorena()
   {
      return this.zatvorena;
   }

   public void setZatvorena(java.lang.String zatvorena)
   {
      this.zatvorena = zatvorena;
   }

   public java.lang.String getPonovno_otvorena()
   {
      return this.ponovno_otvorena;
   }

   public void setPonovno_otvorena(java.lang.String ponovno_otvorena)
   {
      this.ponovno_otvorena = ponovno_otvorena;
   }

   public java.lang.String getVracena_u_obradu()
   {
      return this.vracena_u_obradu;
   }

   public void setVracena_u_obradu(java.lang.String vracena_u_obradu)
   {
      this.vracena_u_obradu = vracena_u_obradu;
   }

   public Statusi_pogresaka(java.lang.Long id_sts_pogr,
         java.lang.String prijavljena, java.lang.String u_obradi,
         java.lang.String ispravljena_programer,
         java.lang.String provjerena, java.lang.String zatvorena,
         java.lang.String ponovno_otvorena, java.lang.String vracena_u_obradu)
   {
      this.id_sts_pogr = id_sts_pogr;
      this.prijavljena = prijavljena;
      this.u_obradi = u_obradi;
      this.ispravljena_programer = ispravljena_programer;
      this.provjerena = provjerena;
      this.zatvorena = zatvorena;
      this.ponovno_otvorena = ponovno_otvorena;
      this.vracena_u_obradu = vracena_u_obradu;
   }

}