package vvgtest.ja;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Statusi implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("StatusID")
   private java.lang.Long id_statusa;
   @org.kie.api.definition.type.Label("U obradi")
   private java.lang.String programiranje;
   @org.kie.api.definition.type.Label("U testiranju")
   private java.lang.String u_testiranju;
   @org.kie.api.definition.type.Label("U analizi")
   private java.lang.String analiza;

   @org.kie.api.definition.type.Label("Produkcija")
   private java.lang.String produkcija;

   @org.kie.api.definition.type.Label("U programiranju")
   private java.lang.String u_obradi;

   @org.kie.api.definition.type.Label("zavrseno")
   private java.lang.String zavrseno;

   @org.kie.api.definition.type.Label("u pripremi testna skripta")
   private String preuzeto;

   private java.lang.Integer id_status;

   public Statusi()
   {
   }

   public java.lang.Long getId_statusa()
   {
      return this.id_statusa;
   }

   public void setId_statusa(java.lang.Long id_statusa)
   {
      this.id_statusa = id_statusa;
   }

   public java.lang.String getProgramiranje()
   {
      return this.programiranje;
   }

   public void setProgramiranje(java.lang.String programiranje)
   {
      this.programiranje = programiranje;
   }

   public java.lang.String getU_testiranju()
   {
      return this.u_testiranju;
   }

   public void setU_testiranju(java.lang.String u_testiranju)
   {
      this.u_testiranju = u_testiranju;
   }

   public java.lang.String getAnaliza()
   {
      return this.analiza;
   }

   public void setAnaliza(java.lang.String analiza)
   {
      this.analiza = analiza;
   }

   public java.lang.String getProdukcija()
   {
      return this.produkcija;
   }

   public void setProdukcija(java.lang.String produkcija)
   {
      this.produkcija = produkcija;
   }

   public java.lang.String getU_obradi()
   {
      return this.u_obradi;
   }

   public void setU_obradi(java.lang.String u_obradi)
   {
      this.u_obradi = u_obradi;
   }

   public java.lang.String getZavrseno()
   {
      return this.zavrseno;
   }

   public void setZavrseno(java.lang.String zavrseno)
   {
      this.zavrseno = zavrseno;
   }

   public java.lang.String getPreuzeto()
   {
      return this.preuzeto;
   }

   public void setPreuzeto(java.lang.String preuzeto)
   {
      this.preuzeto = preuzeto;
   }

   public java.lang.Integer getId_status()
   {
      return this.id_status;
   }

   public void setId_status(java.lang.Integer id_status)
   {
      this.id_status = id_status;
   }

   public Statusi(java.lang.Long id_statusa, java.lang.String programiranje,
         java.lang.String u_testiranju, java.lang.String analiza,
         java.lang.String produkcija, java.lang.String u_obradi,
         java.lang.String zavrseno, java.lang.String preuzeto,
         java.lang.Integer id_status)
   {
      this.id_statusa = id_statusa;
      this.programiranje = programiranje;
      this.u_testiranju = u_testiranju;
      this.analiza = analiza;
      this.produkcija = produkcija;
      this.u_obradi = u_obradi;
      this.zavrseno = zavrseno;
      this.preuzeto = preuzeto;
      this.id_status = id_status;
   }

}