package vvgtest.ja;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Statusi implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "StatusID")
   private java.lang.Long id_statusa;
   @org.kie.api.definition.type.Label(value = "U obradi")
   private java.lang.String programiranje;
   @org.kie.api.definition.type.Label(value = "U programiranju")
   private java.lang.String obrada;
   @org.kie.api.definition.type.Label(value = "U testiranju")
   private java.lang.String u_testiranju;
   @org.kie.api.definition.type.Label(value = "Produkcija")
   private java.lang.String testiranje;
   @org.kie.api.definition.type.Label(value = "U analizi")
   private java.lang.String analiza;

   public Statusi()
   {
   }

   public java.lang.Long getId_statusa()
   {
      return this.id_statusa;
   }

   public void setId_statusa(java.lang.Long id_statusa)
   {
      this.id_statusa = id_statusa;
   }

   public java.lang.String getProgramiranje()
   {
      return this.programiranje;
   }

   public void setProgramiranje(java.lang.String programiranje)
   {
      this.programiranje = programiranje;
   }

   public java.lang.String getObrada()
   {
      return this.obrada;
   }

   public void setObrada(java.lang.String obrada)
   {
      this.obrada = obrada;
   }

   public java.lang.String getU_testiranju()
   {
      return this.u_testiranju;
   }

   public void setU_testiranju(java.lang.String u_testiranju)
   {
      this.u_testiranju = u_testiranju;
   }

   public java.lang.String getTestiranje()
   {
      return this.testiranje;
   }

   public void setTestiranje(java.lang.String testiranje)
   {
      this.testiranje = testiranje;
   }

   public java.lang.String getAnaliza()
   {
      return this.analiza;
   }

   public void setAnaliza(java.lang.String analiza)
   {
      this.analiza = analiza;
   }

   public Statusi(java.lang.Long id_statusa, java.lang.String programiranje,
         java.lang.String obrada, java.lang.String u_testiranju,
         java.lang.String testiranje, java.lang.String analiza)
   {
      this.id_statusa = id_statusa;
      this.programiranje = programiranje;
      this.obrada = obrada;
      this.u_testiranju = u_testiranju;
      this.testiranje = testiranje;
      this.analiza = analiza;
   }

}