package vvgtest.ja;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class testovi_prihvacanja implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "testPrihva\u0107anjaID")
   private java.lang.Long id_test_prih;
   @org.kie.api.definition.type.Label(value = "TestnaSkriptaID")
   private java.lang.Long id_testne_sripte;
   @org.kie.api.definition.type.Label(value = "ZahtjevID")
   private java.lang.Long id_zahtjeva;
   @org.kie.api.definition.type.Label(value = "naziv testa prihva\u0107anja")
   private java.lang.String naziv;
   @org.kie.api.definition.type.Label(value = "stabilna verzija aplikacija")
   private java.lang.String verzije_aplikacija;
   @org.kie.api.definition.type.Label(value = "naziv aplikacije")
   private java.lang.String naziv_aplikacija;
   @org.kie.api.definition.type.Label(value = "opis")
   private java.lang.String opis_testa_prihvacanja;
   @org.kie.api.definition.type.Label(value = "izvjestaj o spremnosti za produkciju")
   private java.lang.Long id_izvjestaja;
   @org.kie.api.definition.type.Label(value = "korisnik")
   private java.lang.Long id_korisnika;

   public testovi_prihvacanja()
   {
   }

   public java.lang.Long getId_test_prih()
   {
      return this.id_test_prih;
   }

   public void setId_test_prih(java.lang.Long id_test_prih)
   {
      this.id_test_prih = id_test_prih;
   }

   public java.lang.Long getId_testne_sripte()
   {
      return this.id_testne_sripte;
   }

   public void setId_testne_sripte(java.lang.Long id_testne_sripte)
   {
      this.id_testne_sripte = id_testne_sripte;
   }

   public java.lang.Long getId_zahtjeva()
   {
      return this.id_zahtjeva;
   }

   public void setId_zahtjeva(java.lang.Long id_zahtjeva)
   {
      this.id_zahtjeva = id_zahtjeva;
   }

   public java.lang.String getNaziv()
   {
      return this.naziv;
   }

   public void setNaziv(java.lang.String naziv)
   {
      this.naziv = naziv;
   }

   public java.lang.String getVerzije_aplikacija()
   {
      return this.verzije_aplikacija;
   }

   public void setVerzije_aplikacija(java.lang.String verzije_aplikacija)
   {
      this.verzije_aplikacija = verzije_aplikacija;
   }

   public java.lang.String getNaziv_aplikacija()
   {
      return this.naziv_aplikacija;
   }

   public void setNaziv_aplikacija(java.lang.String naziv_aplikacija)
   {
      this.naziv_aplikacija = naziv_aplikacija;
   }

   public java.lang.String getOpis_testa_prihvacanja()
   {
      return this.opis_testa_prihvacanja;
   }

   public void setOpis_testa_prihvacanja(
         java.lang.String opis_testa_prihvacanja)
   {
      this.opis_testa_prihvacanja = opis_testa_prihvacanja;
   }

   public java.lang.Long getId_izvjestaja()
   {
      return this.id_izvjestaja;
   }

   public void setId_izvjestaja(java.lang.Long id_izvjestaja)
   {
      this.id_izvjestaja = id_izvjestaja;
   }

   public java.lang.Long getId_korisnika()
   {
      return this.id_korisnika;
   }

   public void setId_korisnika(java.lang.Long id_korisnika)
   {
      this.id_korisnika = id_korisnika;
   }

   public testovi_prihvacanja(java.lang.Long id_test_prih,
         java.lang.Long id_testne_sripte, java.lang.Long id_zahtjeva,
         java.lang.String naziv, java.lang.String verzije_aplikacija,
         java.lang.String naziv_aplikacija,
         java.lang.String opis_testa_prihvacanja,
         java.lang.Long id_izvjestaja, java.lang.Long id_korisnika)
   {
      this.id_test_prih = id_test_prih;
      this.id_testne_sripte = id_testne_sripte;
      this.id_zahtjeva = id_zahtjeva;
      this.naziv = naziv;
      this.verzije_aplikacija = verzije_aplikacija;
      this.naziv_aplikacija = naziv_aplikacija;
      this.opis_testa_prihvacanja = opis_testa_prihvacanja;
      this.id_izvjestaja = id_izvjestaja;
      this.id_korisnika = id_korisnika;
   }

}