package vvgtest.ja;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Vrste_posla implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Vrsta posla")
   private java.lang.Integer id_vrste_posla;
   @org.kie.api.definition.type.Label("Zahtjevi")
   private java.lang.String zahtjevi;
   @org.kie.api.definition.type.Label("Analiza")
   private java.lang.String analiza;
   @org.kie.api.definition.type.Label("Testiranje")
   private java.lang.String testiranje;
   @org.kie.api.definition.type.Label("Programiranje")
   private java.lang.String programiranje;
   @org.kie.api.definition.type.Label(value = "Odabir")
   private boolean odabir;

   public Vrste_posla()
   {
   }

   public java.lang.Integer getId_vrste_posla()
   {
      return this.id_vrste_posla;
   }

   public void setId_vrste_posla(java.lang.Integer id_vrste_posla)
   {
      this.id_vrste_posla = id_vrste_posla;
   }

   public java.lang.String getZahtjevi()
   {
      return this.zahtjevi;
   }

   public void setZahtjevi(java.lang.String zahtjevi)
   {
      this.zahtjevi = zahtjevi;
   }

   public java.lang.String getAnaliza()
   {
      return this.analiza;
   }

   public void setAnaliza(java.lang.String analiza)
   {
      this.analiza = analiza;
   }

   public java.lang.String getTestiranje()
   {
      return this.testiranje;
   }

   public void setTestiranje(java.lang.String testiranje)
   {
      this.testiranje = testiranje;
   }

   public java.lang.String getProgramiranje()
   {
      return this.programiranje;
   }

   public void setProgramiranje(java.lang.String programiranje)
   {
      this.programiranje = programiranje;
   }

   public boolean isOdabir()
   {
      return this.odabir;
   }

   public void setOdabir(boolean odabir)
   {
      this.odabir = odabir;
   }

   public Vrste_posla(java.lang.Integer id_vrste_posla, java.lang.String zahtjevi,
         java.lang.String analiza, java.lang.String testiranje,
         java.lang.String programiranje, boolean odabir)
   {
      this.id_vrste_posla = id_vrste_posla;
      this.zahtjevi = zahtjevi;
      this.analiza = analiza;
      this.testiranje = testiranje;
      this.programiranje = programiranje;
      this.odabir = odabir;
   }

}