package vvgtest.ja;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Vrste_posla implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Vrste_posla() {
    }

}