package vvgtest.ja;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Zahtjevi implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("ZahtjevID")
   private java.lang.Long id_zahtjeva;
   @org.kie.api.definition.type.Label("Naziv zahjeva")
   private java.lang.String naziv_zahtjeva;
   @org.kie.api.definition.type.Label("Kratki opis zahtjeva")
   private java.lang.String opis_zahtjeva;

   @org.kie.api.definition.type.Label("Status zahtjeva")
   private String status_zahtjeva;

   public Zahtjevi()
   {
   }

   public java.lang.Long getId_zahtjeva()
   {
      return this.id_zahtjeva;
   }

   public void setId_zahtjeva(java.lang.Long id_zahtjeva)
   {
      this.id_zahtjeva = id_zahtjeva;
   }

   public java.lang.String getNaziv_zahtjeva()
   {
      return this.naziv_zahtjeva;
   }

   public void setNaziv_zahtjeva(java.lang.String naziv_zahtjeva)
   {
      this.naziv_zahtjeva = naziv_zahtjeva;
   }

   public java.lang.String getOpis_zahtjeva()
   {
      return this.opis_zahtjeva;
   }

   public void setOpis_zahtjeva(java.lang.String opis_zahtjeva)
   {
      this.opis_zahtjeva = opis_zahtjeva;
   }

   public java.lang.String getStatus_zahtjeva()
   {
      return this.status_zahtjeva;
   }

   public void setStatus_zahtjeva(java.lang.String status_zahtjeva)
   {
      this.status_zahtjeva = status_zahtjeva;
   }

   public Zahtjevi(java.lang.Long id_zahtjeva, java.lang.String naziv_zahtjeva,
         java.lang.String opis_zahtjeva, java.lang.String status_zahtjeva)
   {
      this.id_zahtjeva = id_zahtjeva;
      this.naziv_zahtjeva = naziv_zahtjeva;
      this.opis_zahtjeva = opis_zahtjeva;
      this.status_zahtjeva = status_zahtjeva;
   }

}