package vvgtest.ja;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Zahtjevi implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("ZahtjevID")
   private java.lang.Long id_zahtjeva;
   @org.kie.api.definition.type.Label("Naziv zahjeva")
   private java.lang.String naziv_zahtjeva;
   @org.kie.api.definition.type.Label("Kratki opis zahtjeva")
   private java.lang.String opis_zahtjeva;

   @org.kie.api.definition.type.Label(value = "Status zahtjeva")
   private java.lang.String id_statusa;

   @org.kie.api.definition.type.Label(value = "Poslovni Centar")
   private java.lang.String poslovniCentarID;

   @org.kie.api.definition.type.Label(value = "Opis poslovnih pravila")
   private java.lang.String korisnicka_specifikacija;

   public Zahtjevi()
   {
   }

   public java.lang.Long getId_zahtjeva()
   {
      return this.id_zahtjeva;
   }

   public void setId_zahtjeva(java.lang.Long id_zahtjeva)
   {
      this.id_zahtjeva = id_zahtjeva;
   }

   public java.lang.String getNaziv_zahtjeva()
   {
      return this.naziv_zahtjeva;
   }

   public void setNaziv_zahtjeva(java.lang.String naziv_zahtjeva)
   {
      this.naziv_zahtjeva = naziv_zahtjeva;
   }

   public java.lang.String getOpis_zahtjeva()
   {
      return this.opis_zahtjeva;
   }

   public void setOpis_zahtjeva(java.lang.String opis_zahtjeva)
   {
      this.opis_zahtjeva = opis_zahtjeva;
   }

   public java.lang.String getId_statusa()
   {
      return this.id_statusa;
   }

   public void setId_statusa(java.lang.String id_statusa)
   {
      this.id_statusa = id_statusa;
   }

   public java.lang.String getPoslovniCentarID()
   {
      return this.poslovniCentarID;
   }

   public void setPoslovniCentarID(java.lang.String poslovniCentarID)
   {
      this.poslovniCentarID = poslovniCentarID;
   }

   public java.lang.String getKorisnicka_specifikacija()
   {
      return this.korisnicka_specifikacija;
   }

   public void setKorisnicka_specifikacija(
         java.lang.String korisnicka_specifikacija)
   {
      this.korisnicka_specifikacija = korisnicka_specifikacija;
   }

   public Zahtjevi(java.lang.Long id_zahtjeva, java.lang.String naziv_zahtjeva,
         java.lang.String opis_zahtjeva, java.lang.String id_statusa,
         java.lang.String poslovniCentarID,
         java.lang.String korisnicka_specifikacija)
   {
      this.id_zahtjeva = id_zahtjeva;
      this.naziv_zahtjeva = naziv_zahtjeva;
      this.opis_zahtjeva = opis_zahtjeva;
      this.id_statusa = id_statusa;
      this.poslovniCentarID = poslovniCentarID;
      this.korisnicka_specifikacija = korisnicka_specifikacija;
   }

}